from toolbox.core.training_example import TrainingExample
from toolbox.filters.training_example_filter import TrainingExampleFilter


class RefusalFilter(TrainingExampleFilter):
    '''
    Filter out training examples where the model refuses to comply with the
    user's request.
    '''

    def should_keep(self, example: TrainingExample) -> bool:
        generation = example.generation.lower()
        for bad_phrase in _TIER_1_BAD_PHRASES:
            if bad_phrase in generation:
                return False
        return True


# Taken from the dataset card in:
# https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered
# Then expanded to catch some more stuff.
_TIER_1_BAD_PHRASES = [
    "as an ai language model",
    "text-based ai language model",
    "domestic violence",
    "please refrain",
    "derogatory",
    "inappropriate",
    "offensive",
    "racism",
    "racist",
    "racial",
    "discriminate",
    "discriminatory",
    "discrimination",
    "sexist",
    "sexism",
    "unacceptable",
    "inclusive workplace",
    "lgbt",
    "morals",
    "ethics",
    "ethical",
    "legality",
    "illegal",
    "illegality",
    "hateful",
    "harmful",
    "it is never okay",
    "it is important to",
    "it's important to",
    "real-world consequences",
    "hate speech",
    "glorify",
    "not be appropriate",
    "supremacist",
    "extremist",
    "responsible ai",
    "ai principles",
    "ai assistant",
    "an ai language",
    "ableist",
    "hurtful",
    "gender stereotype",
    "gender inequality",
    "underrepresentation",
    "safe spaces",
    "gender-based",
    "inclusivity",
    "feminist",
    "feminism",
    "transgender",
    "empowerment",
    "communist",
    "capitalism",
    "stereotypes",
    "biases",
    "bias",
    "microaggression",
    "prioritize human safety",
    "as a language model",
    "as an ai language model",
    "as a large language model",
    "as an ai",
    "ethical principles",
    "consensual",
    "it is not appropriate",
    "it's not appropriate",
    "i cannot fulfill your request",
    "harmful to human beings",
    "ethical guidelines",
    "my guidelines",
    "prioritize user safety",
    "adhere to ethical guidelines",
    "harmful consequences",
    "potentially harmful",
    "dangerous activities",
    "promote safety",
    "well-being of all users",
    "responsible information sharing",
    "jeopardize the safety",
    "illegal actions or intentions",
    "undermine the stability",
    "promote the well-being",
    "illegal activities or actions",
    "adherence to the law",
    "potentially be harmful",
    "illegal substances or activities",
    "committed to promoting",
    "safe information",
    "lawful information",
    "cannot provide guidance",
    "cannot provide information",
    "unable to offer assistance",
    "cannot engage in discussions",
    "programming prohibits",
    "follow ethical guidelines",
    "ensure the safety",
    "involves an illegal subject",
    "prioritize safety",
    "illegal subject",
    "prioritize user well-being",
    "cannot support or promote",
    "activities that could harm",
    "pose a risk to others",
    "against my programming",
    "activities that could undermine",
    "potentially dangerous",
    "not within the scope",
    "designed to prioritize safety",
    "not able to provide",
    "maintain user safety",
    "adhere to safety guidelines",
    "dangerous or harmful",
    "cannot provide any information",
    "focus on promoting safety",
    "openai",
    "chatgpt",
]