---
# Airoboros
AesirRoleplayTask:
  custom_prompts:
  dataset_name: "aesir"
  filters:
    - ExactDedupFilter
# Airoboros
AiroborosInstructionFollowingTask:
  custom_prompts:
  dataset_name: "airoboros"
  filters:
    - ExactDedupFilter
    - LlmSlopFilter
    - RefusalFilter
# AI Town
AiTownRoleplayTask:
  custom_prompts:
  dataset_name: "aitown"
  filters:
    - ExactDedupFilter
    - LlmSlopFilter
    - RefusalFilter
# CAI
CharacterAiRoleplayTask:
  custom_prompts:
  dataset_name: "characterai"
  filters:
    - EnglishFilter
    - ExactDedupFilter
    - LlmSlopFilter
    - RefusalFilter
    - SimilarityFilter
  timestamp_cutoff: -1
# no_robots
NoRobotsInstructionFollowingTask:
  custom_prompts:
  dataset_name: "no_robots"
  filters:
    - ExactDedupFilter
    - RefusalFilter
# OpenCAI
OpenCaiRoleplayTask:
  custom_prompts:
  dataset_name: "opencai"
  filters:
    - EnglishFilter
    - ExactDedupFilter
# Pyg-submitted Claude logs
PygClaudeRoleplayTask:
  custom_prompts:
  dataset_name: "pyg-claude"
  filters:
    - ExactDedupFilter
    - LlmSlopFilter
    - RefusalFilter
# RP forums
RpForumsRoleplayTask:
  custom_prompts:
  dataset_name: "rpforums"
  filters:
    - ExactDedupFilter
    - LowQualityRpFilter
  remove_ooc: true
# Teatime
TeatimeRoleplayTask:
  # Valid models: 'claude-v1-100k', 'gpt-3.5-turbo-0301', 'gpt-4-0314', 'claude-v1.2', 'claude-1.3-100k', 'claude-1.2', 'gpt-3.5-turbo-16k-0613'
  allowed_models:
    - claude-v1-100k
    - claude-v1.2
    - claude-1.3-100k
    - claude-1.2
  custom_prompts:
  dataset_name: "teatime"
  filters:
    - EnglishFilter
    - ExactDedupFilter
    - LlmSlopFilter
    - RefusalFilter
...
