# Pydantic base classes for datasets and tasks
from pydantic import BaseModel, Field

class CompileConfig(BaseModel):
    # Output options.
    output_name: str = Field(default="dataset", description="If saving the dataset as a singular file, this is the filename to use (without extension).\nIf output_format is 'hf_dataset', then this field is ignored.")
    output_format: str = Field(default="hf_dataset", description="The format to save the compiled dataset in. Options are 'hf_dataset' (a HuggingFace dataset folder), 'json' (a JSONL file), or 'parquet' (a Parquet file).")
    output_path: str = Field(..., description="Path to save the compiled dataset to.")

    # HuggingFace Hub options.
    hf_repo_name: str | None = Field(default=None, description="If pushing to the HuggingFace Hub, this is the name of the repository to create/use. If empty, will use `output_name`.")
    hf_private: bool = Field(default=False, description="Whether the dataset repository should be private when pushing to the HuggingFace Hub.")
    hf_token: str | None = Field(default=None, description="The HuggingFace Hub token to use when pushing the dataset. If empty, will attempt to use the token found in the HuggingFace cache.")
    push_to_hub: bool = Field(default=False, description="Whether to push the compiled dataset to the HuggingFace Hub after saving it locally.")

class TaskConfig(BaseModel):
    name: str = Field(..., description="The name of the task to generate. This should correspond to a subclass of `toolbox.core.task.Task` or its shorthand alias.")
    split: str = Field(default="train", description="The split of the dataset to use (e.g. 'train', 'test', 'validation') if using a HuggingFace Dataset. Default is 'train'.")
    filters: list[str] = Field(default=[], description="A list of filters to apply to the dataset before saving. Each filter should correspond to a subclass of `toolbox.core.filter.Filter` or its shorthand alias.")
    task_kwargs: dict = Field(default={}, description="A dictionary of keyword arguments to pass to the Task subclass when instantiating it. This is useful for passing in task-specific parameters.")
    max_examples: int | None = Field(default=None, description="If set, limits the number of examples generated by the task to this number. If None, all examples are used. YET TO BE IMPLEMENTED.")
    total_percentage: float | None = Field(default=None, description="If set, limits or expands the dataset via. augmentations to this percentage of the total examples. If None, the number of examples is set by `max_examples` or all examples if `max_examples` is None. YET TO BE IMPLEMENTED.")
